name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get tag name
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
        echo "MAJOR_TAG_NAME=${TAG_NAME%%.*}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install require Node version
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Build and tag action
      run: npm run bundle
    - name: Configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Amend tag
      run: |
        git tag -d $TAG_NAME
        if [ ! -z $(git tag -l $MAJOR_TAG_NAME) ]; then
          git tag -d $MAJOR_TAG_NAME
        fi
        git checkout -b release
        git rm .gitignore
        git add action.yml dist/index.js node_modules
        git commit --amend --no-edit .gitignore action.yml dist/index.js node_modules
        git tag -a -m "version ${TAG_NAME##v}" $TAG_NAME
        git tag -a -m "relink ${MAJOR_TAG_NAME}" $MAJOR_TAG_NAME
        git push --force origin $TAG_NAME
        git push --force origin $MAJOR_TAG_NAME
