name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get tag name
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_ENV
        echo "MAJOR_TAG_NAME=${TAG_NAME%%.*}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Build and tag action
      run: npm run bundle
    - name: Configure git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Amend tag
      run: |
        git add action.yml dist/index.js
        git commit --amend --no-edit
        git tag -a -f -m "version ${TAG_NAME##v}" $TAG_NAME $TAG_NAME^{}
        git push --force origin $TAG_NAME
        if [ -z $(git tag -l $MAJOR_TAG_NAME) ]; then
          git tag -a -m "relink ${MAJOR_TAG_NAME}" $MAJOR_TAG_NAME
        else
          git tag -a -f -m "relink ${MAJOR_TAG_NAME}" $MAJOR_TAG_NAME $MAJOR_TAG_NAME^{}
        fi
        git push --force origin $MAJOR_TAG_NAME
