name: Release
on:
  push:
    tags:
    - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    #- name: Get Release Version
    #  run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
    #- name: Build and Tag Action
    #  run: |
    #    npm run bundle
    #- name: Amend Tag
    #  run: |
    #    git add action.yml dist/index.js dist/*.wasm
    #    git commit --amend --no-edit
    #    git push --force origin ${{ env.RELEASE_VERSION }}
